# Generated by Django 3.1 on 2020-08-16 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('identificacion', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
